# Project information
site_name: Fog Project Documentation (FOG Docs)
site_url: https://docs.fogproject.org
site_author: FOG Project
site_description: >-
  Documentation for the FOG Project computer cloning and image deployment system
# Repository
repo_name: FOGProject/fog-docs
repo_url: https://github.com/FOGProject/fog-docs

# Copyright
copyright: Copyright &copy; 2020 - 2023 FOG Project

#many of these options were taken from the material mkdocs home page so we can quickly use any options documented there
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/favicon.png
  icon:
    logo: logo

extra_css:
  - "assets/css/custom.css"

plugins:
  - search
  - include_dir_to_nav # see also https://pypi.org/project/mkdocs-include-dir-to-nav/ this allows for an auto organized site map
  - roamlinks # added for support of obsidian see also https://about.gitlab.com/blog/2022/03/15/publishing-obsidian-notes-with-gitlab-pages/ and https://github.com/Jackiexiao/mkdocs-roamlinks-plugin
  - callouts
  - tags: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
      tags_file: tags.md

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - nl2br
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables # see also https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - toc:
      permalink: true

nav:
  - Home/Getting Started: 
    - Home: index.md
    - What is Fog?: introduction.md
    - System Requirements: installation/requirements.md
    - Install Fog: installation/install-fog-server.md
    - Capture an Image: kb/how-tos/capture-an-image.md
    - Deploy an Image: kb/how-tos/deploy-an-image.md
  - Installing/Updating: installation
  - Management: 
    - management/README.md
    - Web Management: 
      - management/web/README.md
      - Dashboard: management/web/dashboard.md
      - User Management: management/web/users.md
      - Host Management: management/web/hosts.md
      - Group Management: management/web/groups.md
      - Image Management: management/web/images.md
      - Storage Node Management: management/web/storage-node.md
      - Snapin Management: management/web/snapins.md
      - Printer Management: management/web/printers.md
      - Service Management: management/web/service.md
      - Task Management: management/web/tasks.md
      - Report Management: management/web/reports.md
      - Fog Configuration: 
        - management/web/config.md
        - management/web/config
      - Plugin Management: management/web/plugins.md
  - Knowledge Base: 
    - kb/README.md
    - FAQ: kb/faqs
    - Customization: kb/customization
    - Integrations: kb/integrations
    - How-To Guides: kb/how-tos
    - Troubleshooting: kb/troubleshooting
    - Reference: kb/reference
  - Development: development
  - Tags: tags.md
  - Release Notes: https://github.com/FOGProject/fogproject/blob/master/Release%20Notes.MD
  
# getting started/intro section (quick intro to what fog is vs isn't, links to install instructions, image capture/deploy instructions, etc.)
# install/update/migrate section
# General Management Section (basic use/glossary of the UI once installed)
# KB section (how to guides, troubleshooting guides, general reference docs)
# Development/Contribution Section (stuff like what we've added for making new releases)
