# Project information
site_name: Fog Project Documentation (FOG Docs)
site_url: https://docs.fogproject.org
site_author: FOG Project
site_description: >-
  Documentation for the FOG Project computer cloning and image deployment system
# Repository
repo_name: FOG-Project/fog-docs
repo_url: https://github.com/Fog-Project/fog-docs

# Copyright
copyright: Copyright &copy; 2020 - 2023 FOG Project


theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
  - include_dir_to_nav

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - customization
  - development
  - FAQ
  - getting_started
  - hardware
  - installation
  - integrations
  - introduction
  - management
  - reference
  - troubleshooting
